#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail: msg="{{ item }} is not defined"
  when: not {{ item }}
  with_items:
  - oc_y_cluster_setup_service_groupname
  - oc_y_cluster_setup_deploy_serviceaccount_name
  - oc_y_cluster_setup_prod_front_namespace
  - oc_y_cluster_setup_prod_front_displayname
  - oc_y_cluster_setup_stage_front_namespace
  - oc_y_cluster_setup_stage_front_displayname