# create secret
- name: Set nexus secret template
  template:
    src: nexus_secret.j2
    dest: "{{ tempdir }}/templates/{{ oc_y_cluster_setup_nexus_secret_name }}_{{ namespace }}_secret.yaml"
  vars:
    namespace: "{{ namespace }}"

- name: Set nexus secret
  oc_obj:
    state: present
    name: "{{ oc_y_cluster_setup_nexus_secret_name }}"
    namespace: "{{ namespace }}"
    kind: secret
    files:
    - "{{ tempdir }}/templates/{{ oc_y_cluster_setup_nexus_secret_name }}_{{ namespace }}_secret.yaml"
    delete_after: true
