- import_tasks: check_vars.yml tags=cluster-setup

- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-ansible-y-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Create templates subdirectory
  file:
    state: directory
    path: "{{ tempdir }}/{{ item }}"
    mode: 0755
  changed_when: False
  with_items:
    - templates

- import_tasks: setup_stage_front.yml tags=cluster-setup,cluster-setup:stage
- import_tasks: setup_prod_front.yml tags=cluster-setup,cluster-setup:prod

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False