- name: OpenShift Compare Group Sync LDAP Groups Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Sync LDAP Groups 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_cg_ldap_groups:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

# TODO figure out the reason why this does not work when we move it to the role.
- name: Copy ldap group config
  hosts: oo_first_master
  tasks:
  - name: Deploy ldap group sync configuration files
    copy:
      src: "{{ openshift_ldap_group_config_file }}"
      dest: /etc
      owner: root
      group: root
      mode: 0644
    when: openshift_ldap_group_config_file is defined

- name: OpenShift Compare Group Sync LDAP Groups
  hosts: oo_first_master
  roles:
  - { role: oc_cg_roles/oc-cg-ldap-groups, tags: 'ldap-groups' }

- name: OpenShift Compare Group Sync LDAP Groups End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Sync LDAP Groups 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_cg_ldap_groups:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"