---
- name: OpenShift Compare Group Policies Provisioning Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Policies Provisioning 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_y_policies:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: OpenShift Compare Group Policies Provisioning
  hosts: oo_first_master
  roles:
  - { role: roles/oc-y-policies, tags: 'policies' }

- name: OpenShift Compare Group Policies Provisioning End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Policies Provisioning 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_y_policies:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
