- name: OpenShift Hybris Cluster Setup Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Hybris Cluster Setup 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_y_setup:
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: OpenShift Hybris Cluster Setup
  hosts: oo_first_master
  roles:
  - { role: oc_y_roles/oc-y-cluster-setup, tags: 'cluster-setup' }

- name: OpenShift Hybris Cluster Setup End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Hybris Cluster Setup 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_cg_setup:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
