---
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml
# Setup Hybris Cluster
- import_playbook: oc-y-playbooks/oc-y-cluster-setup/private/config.yml
# Create Ops-View project
- import_playbook: oc-y-playbooks/oc-y-ops-view/private/config.yml