#
# Checking that required variables are set
#
- name: Checking that required variables are set
  fail: msg="{{ item }} is not defined"
  when: not {{ item }}
  with_items:
  - oc_y_ops_view_project_namespace
  - oc_y_ops_view_project_displayname
  - oc_y_ops_view_serviceaccount_name
  - oc_y_ops_view_project_repos_url