- name: Checking that required variables are set
  fail: msg="{{ item }} is not defined"
  when: not {{ item }}
  with_items:
  - openshift_os_firewall_enabled
  - openshift_os_firewall_use_firewalld
  - openshift_os_firewall_allow
  - openshift_os_firewall_deny
