- name: Deploy ldap group sync configuration files
  copy:
    src: "{{ openshift_ldap_group_config_file }}"
    dest: "{{ oc_y_ldap_groups_main_dir }}"
    owner: root
    group: root
    mode: 0644
  when: openshift_ldap_group_config_file is defined